language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
notifications:
  slack: way-cooler:W2vOSvJvgxGi7EiGkZCtvlB6
  email: false
after_failure:
  - ls -R
script:
  - cargo test --verbose
