[package]
name = "way-cooler"
description = "Customizeable Wayland compositor written in Rust"
version = "0.3.2"
repository = "https://github.com/Immington-Industries/way-cooler/"
keywords = ["Wayland", "compositor", "window", "manager", "wlc"]
readme = "README.md"
license = "MIT"
authors = ["Snirk Immington <snirk.immington@gmail.com>", "Timidger <apragmaticplace@gmail.com>"]

[dependencies]
rustwlc = "0.5"
lazy_static = "0.2"
log = "0.3"
env_logger = "0.3"
hlua = "0.1"
bitflags = "0.6"
petgraph = { version = "0.3.1" }
rustc-serialize = "0.3"
json_macro = "0.1"
nix = "0.6"
uuid = { version = "0.3", features = ["v4", "rustc-serialize"]}
wayland-sys = { version = "^0.6.0", features = ["client", "dlopen"] }
wayland-client = { version = "^0.6.0", features = ["cursor", "dlopen"] }
tempfile = "2.1"
byteorder = ">= 0.3, < 0.6"
getopts = "^0.2"

[dev-dependencies]
dummy-rustwlc = { git = "https://github.com/SnirkImmington/dummy-rustwlc.git"}
