[package]
name = "way-cooler"
description = "Customizeable Wayland compositor written in Rust"
version = "0.1.0"
repository = "https://github.com/Immington-Industries/way-cooler/"
keywords = ["wlc", "Wayland", "compositor", "window", "manager"]
readme = "README.md"
license = "MIT"
authors = ["Snirk Immington <snirk.immington@gmail.com>", "Timidger <apragmaticplace@gmail.com>"]

[dependencies]
rustwlc = "^0.3"
lazy_static = "*"
log = "*"
env_logger = "*"
hlua = "^0.1"
rustc-serialize = "^0.3"
